create table employee (id int8 generated by default as identity,
                       name varchar(255), primary key (id));
insert into employee(name) values ('John Doe');
insert into employee(name) values ('Jack Doe');